### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by xrff** [lepfinder/dbmaster#4]
python2.6环境部署失败，报错如下：

[2018-10-08 15:31:31 +0000] [26643] [INFO] Booting worker with pid: 26643
[2018-10-08 15:31:31 +0000] [26648] [INFO] Booting worker with pid: 26648
[2018-10-08 15:31:31 +0000] [26653] [INFO] Booting worker with pid: 26653
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d27290>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d276d0>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2a310>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2a750>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2c390>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2c7d0>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2e410>)
  app.register_module(module, url_prefix=url_prefix)
/opt/dbmaster-master/dbmaster/__init__.py:47: DeprecationWarning: Modules are deprecated.  Upgrade to using blueprints.  Have a look into the documentation for more information.  If this module was registered by a Flask-Extension upgrade the extension or contact the author of that extension instead.  (Registered <flask.module.Module object at 0x2d2e850>)
  app.register_module(module, url_prefix=url_prefix)
[2018-10-08 15:31:39 +0000] [26642] [ERROR] Error handling request /dbmaster/
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.6/site-packages/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/dbmaster-master/dbmaster/views/masterview.py", line 62, in index
    sql_content = query_list[0].content
  File "/usr/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2462, in __getitem__
    return list(self[item:item + 1])[0]
IndexError: list index out of range

**Comment by lepfinder** [comment]
已修复
